name: CentOS7

on: [push]

jobs:
  buildubuntu:
    name: build_centos_7
    runs-on: centos7
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: srt_to_udp_server
        path: ./srt_to_udp_server
